release_*:
  tag_push:
    - name: build_in_ubuntu2404
      runner:
        cpus: 1
      docker:
        image: docker.cnb.cool/dragonos-community/deb-downloader:ubuntu2404-250511
      git:
        enable: true
      env:
        IN_DOCKER: 0
      stages:
        - name: glibc_ubuntu2404
          if: |
              bash -c "[[ "${CNB_BRANCH}" == release_glibc_ubuntu2404_* ]]"

          jobs:
            - name: build
              script:
                - echo "Building in Ubuntu 24.04"
                - bash -c "pushd ./ && cd packages/glibc-ubuntu2404 && bash pack.sh && popd"
            - name: upload_release
              type: git:release
              options:
                title: ${CNB_BRANCH}
            - name: release 上传附件
              image: cnbcool/attachments:latest
              settings:
                attachments:
                  - "./output/*.tar.xz"
